// Removing invalid ThroughLocation INCLUDE lines

// Code for yesterdayQuery
var yesterdayQuery = `SELECT * FROM TrainAnnouncement WHERE ... 
// Previous lines ...
// REMOVE <INCLUDE>ViaLocation</INCLUDE>
...`;

// Code for todayQuery
var todayQuery = `SELECT * FROM TrainAnnouncement WHERE ... 
// Previous lines ...
// REMOVE <INCLUDE>ViaLocation</INCLUDE>
...`;